apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
    - name: sysconfig
      hostPath:
        path: /etc/sysconfig
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
      - name: sysconfig
        mountPath: /mnt/sysconfig
